/**
 * @file Main_DC.cpp
 * @brief Dreamcast entry point — boots the engine, runs the loop, exits clean.
 *
 * Mirrors the desktop Standalone/Source/Main.cpp boot sequence (Oct* hooks ->
 * GameMain) using KallistiOS conventions:
 *
 *   - KOS_INIT_FLAGS(INIT_DEFAULT) sets up the standard KOS runtime (threads,
 *     maple, romdisk if any) before main() runs.
 *   - GameMain() (defined inside Engine.cpp) does the actual boot/update/
 *     shutdown; the engine's own `int main` is gated out when
 *     POLYPHASE_PLATFORM_ADDON is defined, so ours below is the sole entry.
 *
 * Oct* hooks are minimal stubs — a real game project can override by shipping
 * its own Main under Source/. The 640x480 window-size override is forced in
 * BOTH OctPreInitialize and OctPostInitialize (see the PSP port notes: Config.ini
 * reload clobbers the pre-init value, so the post-init re-override is required).
 *
 * Built only when POLYPHASE_PLATFORM_ADDON is defined.
 */

#if defined(POLYPHASE_PLATFORM_ADDON)

#include <kos.h>
#include <stdio.h>

#include "Engine.h"
#include "EmbeddedFile.h"
#include "Log.h"

// Phase-2 bring-up demo scene (spawned only when the project has no scene of its
// own, i.e. no active camera). Exercises the real engine mesh render path.
#include "Engine/Renderer.h"
#include "Engine/World.h"
#include "Engine/AssetManager.h"
#include "Engine/Vertex.h"
#include "Engine/Assets/StaticMesh.h"
#include "Engine/Assets/MaterialLite.h"
#include "Engine/Assets/Texture.h"
#include "Engine/Nodes/3D/StaticMesh3d.h"
#include "Engine/Nodes/3D/Camera3d.h"

// Standard KOS init: threads + maple (controllers) + default drivers. PVR is
// initialised by Graphics_PVR2::GFX_Initialize, not here, so it isn't in the
// flag set.
KOS_INIT_FLAGS(INIT_DEFAULT);

// Embedded-scripts table generated by the editor's packager into
// Generated/EmbeddedScripts.cpp at cook time. Dreamcast loads assets from the
// disc (/cd/) via AssetManager::Discover, but Lua scripts only ship via the
// embedded path, so this one blob is wired into the EngineConfig below.
extern uint32_t gNumEmbeddedScripts;
extern EmbeddedFile gEmbeddedScripts[];

// C++ pure-virtual-call handler. With -fno-exceptions -fno-rtti the sh-elf link
// may not pull libsupc++'s copy, leaving __cxa_pure_virtual undefined against
// every abstract vtable slot. Define it here so the module links.
extern "C" void __cxa_pure_virtual()
{
    printf("FATAL: pure virtual call\n");
    fflush(stdout);
    for (;;) {}
}

// -------------------------------------------------------------------------
// Oct* hooks — minimal stubs, resolved at static-init by the engine's
// OctHookAutoRegister.
// -------------------------------------------------------------------------

void OctPreInitialize(EngineConfig& config)
{
    GetEngineState()->mStandalone = true;

    // Dreamcast video is a fixed 640x480 framebuffer. Set it in the config
    // (belt); OctPostInitialize re-applies it to EngineState (suspenders) after
    // ReadEngineConfig has had its chance to clobber it with the desktop size.
    config.mWindowWidth  = 640;
    config.mWindowHeight = 480;

    config.mEmbeddedScriptCount = gNumEmbeddedScripts;
    config.mEmbeddedScripts     = gEmbeddedScripts;
}

// Phase-2 bring-up: when the loaded project has NO scene of its own (no active
// camera), spawn a rotating shaded cube + camera so the real engine mesh render
// path (GFX_CreateStaticMeshResource + GFX_DrawStaticMeshComp) is exercised.
// A project that ships a scene is untouched (the early-out below). Remove when
// projects reliably provide their own scenes.
static StaticMesh3D* sDemoMeshNode = nullptr;

static void DcSpawnDemoScene()
{
    // GetWorld(0) is the persistent primary world (created at Initialize); the
    // Renderer's "current world" isn't set until the render loop runs, so use the
    // global accessor here at post-init time.
    World* world = GetWorld(0);
    if (world == nullptr) { LogWarning("[DC] demo scene: no world"); return; }
    if (world->GetActiveCamera() != nullptr) return;   // project provided a scene

    static const glm::vec3 P[8] = {
        {-1,-1,-1}, { 1,-1,-1}, { 1, 1,-1}, {-1, 1,-1},
        {-1,-1, 1}, { 1,-1, 1}, { 1, 1, 1}, {-1, 1, 1},
    };
    struct Face { glm::vec3 n; uint32_t col; int i[4]; };
    auto RGBA = [](uint32_t r, uint32_t g, uint32_t b) -> uint32_t {
        return r | (g << 8) | (b << 16) | 0xFF000000u;   // engine packs R low byte
    };
    const Face F[6] = {
        {{ 0, 0,  1}, RGBA(230, 70, 70),  {4, 5, 6, 7}},
        {{ 0, 0, -1}, RGBA(70, 200, 70),  {1, 0, 3, 2}},
        {{ 1, 0,  0}, RGBA(80, 120, 230), {5, 1, 2, 6}},
        {{-1, 0,  0}, RGBA(230, 210, 70), {0, 4, 7, 3}},
        {{ 0, 1,  0}, RGBA(70, 210, 210), {7, 6, 2, 3}},
        {{ 0,-1,  0}, RGBA(210, 70, 210), {0, 1, 5, 4}},
    };

    VertexColor verts[24];
    IndexType   indices[36];
    for (int f = 0; f < 6; ++f)
    {
        for (int k = 0; k < 4; ++k)
        {
            VertexColor& v = verts[f * 4 + k];
            v.mPosition  = P[F[f].i[k]];
            v.mTexcoord0 = glm::vec2(0.0f);
            v.mTexcoord1 = glm::vec2(0.0f);
            v.mNormal    = F[f].n;
            v.mColor     = F[f].col;
        }
        const int b = f * 4, o = f * 6;
        indices[o + 0] = b + 0; indices[o + 1] = b + 1; indices[o + 2] = b + 2;
        indices[o + 3] = b + 0; indices[o + 4] = b + 2; indices[o + 5] = b + 3;
    }

    StaticMesh* mesh = NewTransientAsset<StaticMesh>();
    mesh->CreateRawColor(24, verts, 36, indices);   // sets data + Create() -> GFX upload

    Camera3D* cam = world->SpawnNode<Camera3D>(glm::vec3(0.0f, 0.0f, 10.0f));
    cam->SetPosition(glm::vec3(0.0f, 0.0f, 10.0f));   // explicit, in case spawn arg isn't applied
    world->SetActiveCamera(cam);

    StaticMesh3D* node = world->SpawnNode<StaticMesh3D>(glm::vec3(0.0f, 0.0f, 0.0f));
    node->SetStaticMesh(mesh);
    node->SetRotation(glm::vec3(20.0f, 30.0f, 0.0f));   // tilt so three faces show
    sDemoMeshNode = node;

    LogDebug("[DC] Phase-2 demo scene spawned (cube + camera)");
}

#if 0   // Removed: translucent/masked blend-demo scaffolding (DcBuildUvCube + DcSpawnBlendDemo).
// A unit cube with per-face UVs (0..1) and white vertex colour, for the blend
// demo below.
static StaticMesh* DcBuildUvCube()
{
    static const glm::vec3 P[8] = {
        {-1,-1,-1}, { 1,-1,-1}, { 1, 1,-1}, {-1, 1,-1},
        {-1,-1, 1}, { 1,-1, 1}, { 1, 1, 1}, {-1, 1, 1},
    };
    struct Face { glm::vec3 n; int i[4]; };
    const Face F[6] = {
        {{ 0, 0, 1}, {4, 5, 6, 7}}, {{ 0, 0,-1}, {1, 0, 3, 2}}, {{ 1, 0, 0}, {5, 1, 2, 6}},
        {{-1, 0, 0}, {0, 4, 7, 3}}, {{ 0, 1, 0}, {7, 6, 2, 3}}, {{ 0,-1, 0}, {0, 1, 5, 4}},
    };
    static const glm::vec2 UV[4] = { {0,0}, {1,0}, {1,1}, {0,1} };
    VertexColor verts[24];
    IndexType   indices[36];
    for (int f = 0; f < 6; ++f)
    {
        for (int k = 0; k < 4; ++k)
        {
            VertexColor& v = verts[f * 4 + k];
            v.mPosition  = P[F[f].i[k]];
            v.mTexcoord0 = UV[k];
            v.mTexcoord1 = UV[k];
            v.mNormal    = F[f].n;
            v.mColor     = 0xFFFFFFFF;
        }
        const int b = f * 4, o = f * 6;
        indices[o + 0] = b + 0; indices[o + 1] = b + 1; indices[o + 2] = b + 2;
        indices[o + 3] = b + 0; indices[o + 4] = b + 2; indices[o + 5] = b + 3;
    }
    StaticMesh* mesh = NewTransientAsset<StaticMesh>();
    mesh->CreateRawColor(24, verts, 36, indices);
    return mesh;
}

// Spawn a translucent cube and a masked (alpha-cutout) cube so both PVR blend
// paths are visible. Temporary demo — remove once scenes provide their own
// translucent/masked content.
static void DcSpawnBlendDemo()
{
    World* world = GetWorld(0);
    if (world == nullptr) return;
    StaticMesh* cube = DcBuildUvCube();

    // Translucent: blue, 50% opacity — you can see through it (TR list, blended).
    {
        MaterialLite* mat = NewTransientAsset<MaterialLite>();
        MaterialLiteParams mp = mat->GetLiteParams();
        mp.mShadingModel = ShadingModel::Unlit;
        mp.mBlendMode    = BlendMode::Translucent;
        mp.mNumTextures  = 0;
        mp.mColor        = glm::vec4(0.3f, 0.6f, 1.0f, 1.0f);
        mp.mOpacity      = 0.5f;
        mat->SetLiteParams(mp);
        mat->Create();

        StaticMesh3D* node = world->SpawnNode<StaticMesh3D>();
        node->SetPosition(glm::vec3(-3.5f, 2.0f, 1.0f));
        node->SetStaticMesh(cube);
        node->SetMaterialOverride(mat);
        node->SetRotation(glm::vec3(15.0f, 25.0f, 0.0f));
    }

    // Masked: a checkerboard alpha texture — transparent squares are cut out
    // (PT list, alpha-tested), leaving hard-edged holes.
    {
        uint8_t px[16 * 16 * 4];
        for (int y = 0; y < 16; ++y)
            for (int x = 0; x < 16; ++x)
            {
                uint8_t* p = &px[(y * 16 + x) * 4];
                const bool opaque = (((x / 4) + (y / 4)) & 1) == 0;
                p[0] = 255; p[1] = 200; p[2] = 60; p[3] = opaque ? 255 : 0;
            }
        Texture* tex = NewTransientAsset<Texture>();
        tex->Init(16, 16, px);
        tex->Create();

        MaterialLite* mat = NewTransientAsset<MaterialLite>();
        MaterialLiteParams mp = mat->GetLiteParams();
        mp.mShadingModel = ShadingModel::Unlit;
        mp.mBlendMode    = BlendMode::Masked;
        mp.mNumTextures  = 1;
        mp.mTextures[0]  = tex;
        mp.mColor        = glm::vec4(1.0f);
        mat->SetLiteParams(mp);
        mat->Create();

        StaticMesh3D* node = world->SpawnNode<StaticMesh3D>();
        node->SetPosition(glm::vec3(3.5f, 2.0f, 1.0f));
        node->SetStaticMesh(cube);
        node->SetMaterialOverride(mat);
        node->SetRotation(glm::vec3(15.0f, -25.0f, 0.0f));
    }

    LogDebug("[DC] blend-mode demo spawned (translucent + masked cubes)");
}
#endif   // Removed blend-demo scaffolding

void OctPostInitialize()
{
    // ReadEngineConfig (inside GameMain) reloads Config.ini AFTER
    // OctPreInitialize and overwrites the 640x480 with the project's authored
    // desktop size; Initialize then copies that into EngineState. Re-force it
    // here so Renderer::GetViewportWidth/Height (read live every frame) sees
    // the native DC resolution. PostPackage also rewrites the packaged
    // Config.ini to 640x480, but this defends manual/older packages too.
    const uint32_t beforeW = GetEngineState()->mWindowWidth;
    const uint32_t beforeH = GetEngineState()->mWindowHeight;
    GetEngineState()->mWindowWidth  = 640;
    GetEngineState()->mWindowHeight = 480;
    LogDebug("[DC] OctPostInitialize: window %ux%u -> 640x480", beforeW, beforeH);

    DcSpawnDemoScene();
}

void OctPreUpdate()
{
    // Spin the demo cube (no-op when a real scene is present).
    if (sDemoMeshNode != nullptr)
        sDemoMeshNode->AddRotation(glm::vec3(0.5f, 0.8f, 0.0f));
}
void OctPostUpdate() {}
void OctPreShutdown() {}
void OctPostShutdown() {}

// -------------------------------------------------------------------------
// Entry. GameMain (Engine/Source/Engine/Engine.cpp) bundles
// ReadCommandLineArgs -> OctPreInitialize -> Initialize -> OctPostInitialize
// -> loop(Update) -> Shutdown.
// -------------------------------------------------------------------------

extern void GameMain(int32_t argc, char** argv);

// SYS_Log routing hook (defined in System_DC.cpp); left at its printf default
// for this diagnostic.
extern void (*gDcLogSink)(const char* line);

// ---- No-op C++ exception-frame registration -------------------------------
// Linked via -Wl,--wrap. frame_dummy calls __register_frame_info at static init
// to register the .eh_frame table for exception unwinding; on SH4/KOS the
// libgcc-internal object_mutex lock no-ops at that point and its unlock asserts,
// aborting boot. We build -fno-exceptions so unwinding is never used — skip the
// registration entirely. (If C++ exceptions are ever needed on DC, fix the KOS
// early-boot mutex instead of no-opping these.)
extern "C" void __wrap___register_frame_info(const void* /*begin*/, void* /*ob*/) {}
extern "C" void* __wrap___deregister_frame_info(const void* /*begin*/) { return 0; }

// Safety net: log any genuine bad mutex unlock (count<=0 = not locked) to serial
// with its caller, so a future imbalance is diagnosable. IRQ-context unlocks
// (holder==IRQ_THREAD, count==1) are valid and skipped by the count check.
extern "C" int __real_mutex_unlock(mutex_t* m);
extern "C" int __wrap_mutex_unlock(mutex_t* m)
{
    if (m != NULL && m->count <= 0)
    {
        printf("[BAD-UNLOCK] ret=%p m=%p holder=%p cur=%p count=%d\n",
               __builtin_return_address(0), (void*)m, (void*)m->holder,
               (void*)thd_current, m->count);
    }
    return __real_mutex_unlock(m);
}

// ---- Single-threaded static-init guards -----------------------------------
// libstdc++'s __cxa_guard_acquire (function-local `static` init guard) locks a
// recursive __gnu_cxx::__mutex via KOS mutex_lock, which fails during C++ static
// init (see the mutex fix below) -> __throw_concurrence_lock_error -> (unwinding
// is stripped by the frame-info no-ops) -> infinite exception re-throw, which was
// the original boot hang. On the Dreamcast all global/static constructors run
// single-threaded on the kernel thread before main(), so thread-safe guards are
// unnecessary. Replace them with trivial non-atomic versions (identical to what
// -fno-threadsafe-statics emits inline): no mutex, no throw. The Itanium ABI
// guard's first byte is the "initialized" flag.
extern "C" int __wrap___cxa_guard_acquire(unsigned long long* g)
{
    return *reinterpret_cast<volatile char*>(g) == 0;
}
extern "C" void __wrap___cxa_guard_release(unsigned long long* g)
{
    *reinterpret_cast<volatile char*>(g) = 1;
}
extern "C" void __wrap___cxa_guard_abort(unsigned long long* /*g*/) {}

// SYSTEMIC KOS/libstdc++ mutex fix. KOS mutex_lock() spuriously rejects
// libstdc++'s statically-initialized mutexes (both normal and recursive) during
// C++ static init — seen from __cxa_guard_acquire, __exchange_and_add (refcount),
// etc. — returning nonzero and driving __throw_concurrence_lock_error into an
// infinite re-throw (unwinding is stripped). All boot-time locking is
// single-threaded on the kernel thread, so when the real lock fails on an
// UNCONTENDED mutex (holder==NULL) we force-acquire it: set holder=current,
// count=1. The paired mutex_unlock (same thread) then satisfies KOS's
// owner+count assertion and releases cleanly. Genuinely contended failures
// (holder!=NULL) are left to fail. A counter logs the first few for visibility.
extern "C" int __real_mutex_lock(mutex_t*);
extern "C" int __wrap_mutex_lock(mutex_t* m)
{
    int rv = __real_mutex_lock(m);
    if (rv != 0 && m != NULL && m->holder == NULL)
    {
        // Uncontended mutex KOS spuriously rejected — force-acquire it.
        m->holder = thd_current;
        m->count  = 1;
        return 0;
    }
    return rv;
}

// ---- SH4 exception catcher (debug aid) ------------------------------------
// A global SH4 exception handler that, on an otherwise-fatal fault, dumps the
// faulting PC to serial and paints the screen red, then spins. It is
// EXCEPTION-CONTEXT SAFE: it must NOT call bfont (bfont_draw_* internally calls
// thd_poll, which asserts !irq_inside_int() and secondary-crashes) or stdio
// printf (locks). snprintf to a stack buffer (no locks) + dbgio_write_str
// (busy-polled SCIF, no thd_poll) + a direct-VRAM fill are all safe. It draws
// nothing at boot, only on an actual fault — invaluable on real hardware.
static volatile int sInExc = 0;

static void DcExcHandler(irq_t code, irq_context_t* ctx, void* data)
{
    (void)data;
    // KOS calls the global handler FIRST on EVERY interrupt/exception, then the
    // specific handler. So this fires on every scheduler timer tick (TMU0=0x400)
    // and every external IRQ — we MUST return for those so KOS's timer/scheduler
    // keeps running. Act only on genuine CPU faults (EXPEVT): TLB miss/protection,
    // address error (unaligned/bad pointer), illegal instruction, FPU.
    switch ((unsigned)code)
    {
        case 0x040: case 0x060:   // TLB miss (read/write)
        case 0x0a0: case 0x0c0:   // TLB protection violation
        case 0x0e0: case 0x100:   // address error (read/write)
        case 0x180: case 0x1a0:   // illegal / slot-illegal instruction
        case 0x800: case 0x820:   // FPU exception
            break;                // real fault -> report + freeze
        default:
            return;               // interrupt / TRAPA / etc. -> let KOS handle
    }
    if (sInExc) { for (;;) {} }
    sInExc = 1;
    char msg[160];
    snprintf(msg, sizeof(msg),
             "\n*** SH4 EXCEPTION *** PC=%08lx CODE=%03x -- photograph this\n",
             (unsigned long)CONTEXT_PC(*ctx), (unsigned)code);
    dbgio_write_str(msg);
    vid_set_mode(DM_640x480, PM_RGB565);
    for (int i = 0; i < 640 * 480; ++i) vram_s[i] = 0xF800; // red
    for (;;) {}
}

__attribute__((constructor(101)))
static void DcArmExcHandler(void)
{
    arch_irq_set_global_handler(&DcExcHandler, NULL);
}

static int    sArgc = 0;
static char** sArgv = nullptr;

static void* EngineThread(void* /*param*/)
{
    GameMain(sArgc, sArgv);
    return nullptr;
}

int main(int argc, char** argv)
{
    (void)gDcLogSink;

    // Route stdout (and thus the engine's SYS_Log/printf) to the SCIF serial
    // port so flycast's Serial Console shows the boot log live. The last line
    // before the crash pinpoints the faulting subsystem. setbuf(NULL) so nothing
    // is lost when the SH4 faults.
    dbgio_dev_select("scif");
    setbuf(stdout, NULL);
    printf("=== Polyphase Dreamcast boot (serial) ===\n");

    sArgc = argc;
    sArgv = argv;

    // KOS's default main-thread stack is only 32 KB (THD_STACK_SIZE) — too small
    // for the engine's init (deep call chains, large scene/reflection frames).
    // Run GameMain on a dedicated 2 MB-stack thread.
    kthread_attr_t attr = {};
    attr.stack_size = 2 * 1024 * 1024;
    attr.prio       = PRIO_DEFAULT;
    attr.label      = "polyphase";
    kthread_t* engine = thd_create_ex(&attr, EngineThread, NULL);
    if (engine != NULL)
        thd_join(engine, NULL);
    else
        GameMain(argc, argv);

    return 0;
}

#endif // POLYPHASE_PLATFORM_ADDON
